const STORAGE_KEY='samenThuisDataV1';
const todayISO=()=>new Date().toISOString().slice(0,10);
const addDays=(date,n)=>{const d=new Date(date);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const initialData={
  planning:[{id:'p1',title:'Samen koken',date:todayISO(),time:'18:30',person:'Samen'}],
  meals:[{id:'m1',date:todayISO(),type:'Avondeten',title:'Tomaten-arancini met basilicummayonaise'}],
  groceries:[{id:'g1',title:'Tomaten',category:'Groente',done:false},{id:'g2',title:'Basilicum',category:'Groente',done:false},{id:'g3',title:'Havermelk',category:'Zuivel & vega',done:true}],
  chores:[{id:'c1',title:'Keuken opruimen',person:'Samen',due:todayISO(),repeat:'Dagelijks',done:false},{id:'c2',title:'Bed verschonen',person:'Kees',due:addDays(todayISO(),2),repeat:'Wekelijks',done:false},{id:'c3',title:'Badkamer schoonmaken',person:'Daphne',due:addDays(todayISO(),1),repeat:'Wekelijks',done:false}],
  stock:[{id:'s1',title:'Toiletpapier',category:'Badkamer',amount:5,min:3,unit:'rollen'},{id:'s2',title:'Pasta',category:'Voorraadkast',amount:2,min:2,unit:'pakken'},{id:'s3',title:'Afwasmiddel',category:'Schoonmaak',amount:1,min:2,unit:'flessen'}],
  ideas:[{id:'i1',title:'Zelf pizza maken',category:'Thuis',note:'Allebei een eigen pizza beleggen',icon:'🍕'},{id:'i2',title:'Avondwandeling',category:'Gratis',note:'Telefoons thuislaten',icon:'🌙'},{id:'i3',title:'Nieuw restaurant proberen',category:'Uit',note:'Een vegetarisch restaurant kiezen',icon:'🍽️'}],
  home:[{id:'h1',title:'Rookmelder testen',category:'Onderhoud',due:addDays(todayISO(),14),note:'Testknop indrukken'},{id:'h2',title:'Afmetingen woonkamer',category:'Woninginfo',due:'',note:'Nog toevoegen'}],
  trips:[{id:'r1',title:'Vietnam',date:'2027-01-08',type:'Reis',note:'Bruiloft in Nha Trang op 29 januari'},{id:'r2',title:'Paspoorten controleren',date:addDays(todayISO(),7),type:'Voorbereiding',note:'Controleer geldigheid'}]
};

let data=loadData();
let current='today';
const sections={
  today:{label:'Vandaag',icon:'⌂'},planning:{label:'Planning',icon:'▦'},meals:{label:'Weekmenu',icon:'♨'},groceries:{label:'Boodschappen',icon:'✓'},chores:{label:'Huishouden',icon:'⌁'},stock:{label:'Voorraad',icon:'▤'},ideas:{label:'Samen doen',icon:'♡'},home:{label:'Woning',icon:'⌂'},trips:{label:'Reizen',icon:'✈'}
};
const formConfig={
 planning:{title:'Afspraak toevoegen',fields:[['title','Wat?','text'],['date','Datum','date'],['time','Tijd','time'],['person','Voor wie?','select',['Samen','Kees','Daphne']]]},
 meals:{title:'Gerecht toevoegen',fields:[['title','Gerecht','text'],['date','Datum','date'],['type','Moment','select',['Ontbijt','Lunch','Avondeten','Snack']]]},
 groceries:{title:'Boodschap toevoegen',fields:[['title','Product','text'],['category','Categorie','select',['Groente','Fruit','Brood','Zuivel & vega','Voorraadkast','Drinken','Schoonmaak','Overig']]]},
 chores:{title:'Taak toevoegen',fields:[['title','Taak','text'],['person','Voor wie?','select',['Samen','Kees','Daphne']],['due','Wanneer?','date'],['repeat','Herhaling','select',['Eenmalig','Dagelijks','Wekelijks','Maandelijks']]]},
 stock:{title:'Voorraad toevoegen',fields:[['title','Product','text'],['category','Plek','select',['Voorraadkast','Koelkast','Vriezer','Badkamer','Schoonmaak','Overig']],['amount','Aantal','number'],['min','Minimum','number'],['unit','Eenheid','text']]},
 ideas:{title:'Idee toevoegen',fields:[['title','Idee','text'],['category','Categorie','select',['Thuis','Uit','Actief','Gratis','Eten']],['note','Notitie','textarea'],['icon','Emoji','text']]},
 home:{title:'Woningitem toevoegen',fields:[['title','Onderwerp','text'],['category','Categorie','select',['Onderhoud','Klus','Garantie','Woninginfo','Handleiding']],['due','Datum (optioneel)','date'],['note','Notitie','textarea']]},
 trips:{title:'Reisitem toevoegen',fields:[['title','Onderwerp','text'],['date','Datum','date'],['type','Soort','select',['Reis','Voorbereiding','Reservering','Paklijst']],['note','Notitie','textarea']]}
};

function loadData(){try{return {...structuredClone(initialData),...JSON.parse(localStorage.getItem(STORAGE_KEY))}}catch{return structuredClone(initialData)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));const el=document.querySelector('#saveState');el.textContent='Zojuist bewaard';setTimeout(()=>el.textContent='Lokaal bewaard',1200)}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(v,options={weekday:'short',day:'numeric',month:'short'}){if(!v)return 'Geen datum';return new Intl.DateTimeFormat('nl-NL',options).format(new Date(v+'T12:00:00'))}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}

function setupNav(){document.querySelector('#nav').innerHTML=Object.entries(sections).map(([k,v])=>`<button class="nav-item ${k===current?'active':''}" data-view="${k}"><span>${v.icon}</span>${v.label}</button>`).join('')}
function navigate(view){current=view;setupNav();document.querySelector('#pageTitle').textContent=sections[view].label;document.querySelector('#addBtn').style.display=view==='today'?'none':'';render()}
function render(){const fn={today:renderToday,planning:renderPlanning,meals:renderMeals,groceries:renderGroceries,chores:renderChores,stock:renderStock,ideas:renderIdeas,home:renderHome,trips:renderTrips}[current];document.querySelector('#view').innerHTML=fn()}
const empty=msg=>`<div class="empty">${msg}</div>`;

function renderToday(){
 const pending=data.chores.filter(x=>!x.done&&x.due<=todayISO());const low=data.stock.filter(x=>+x.amount<=+x.min);const unbought=data.groceries.filter(x=>!x.done);const meal=data.meals.find(x=>x.date===todayISO()&&x.type==='Avondeten');
 return `<section class="card welcome"><div><p class="eyebrow" style="color:#f2b994">Jullie thuis, in één oogopslag</p><h2>Fijn dat jullie er zijn.</h2><p>${meal?`Vanavond staat <strong>${esc(meal.title)}</strong> op het menu.`:'Plan samen wat er vanavond op tafel komt.'}</p></div><div class="date-chip">${fmtDate(todayISO(),{weekday:'long',day:'numeric',month:'long'})}</div></section>
 <div class="stat-row"><div class="stat"><strong>${pending.length}</strong><span>taken voor vandaag</span></div><div class="stat"><strong>${unbought.length}</strong><span>boodschappen open</span></div><div class="stat"><strong>${low.length}</strong><span>producten bijna op</span></div><div class="stat"><strong>${data.planning.filter(x=>x.date===todayISO()).length}</strong><span>afspraken vandaag</span></div></div>
 <div class="grid two"><section class="card"><div class="card-head"><h2>Vandaag te doen</h2><button class="text-btn" data-view="chores">Alle taken</button></div><div class="list">${pending.length?pending.slice(0,5).map(choreRow).join(''):empty('Alles is voor vandaag gedaan 🎉')}</div></section>
 <section class="card"><div class="card-head"><h2>Op de planning</h2><button class="text-btn" data-view="planning">Week bekijken</button></div><div class="list">${data.planning.filter(x=>x.date>=todayISO()).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,5).map(x=>basicRow(x.title,`${fmtDate(x.date)} · ${x.time||'Hele dag'}`,x.person)).join('')||empty('Nog niets gepland')}</div></section>
 <section class="card"><div class="card-head"><h2>Boodschappen</h2><button class="text-btn" data-view="groceries">Open lijst</button></div><div class="list">${unbought.slice(0,5).map(groceryRow).join('')||empty('De lijst is leeg')}</div></section>
 <section class="card"><div class="card-head"><h2>Bijna op</h2><button class="text-btn" data-view="stock">Voorraad bekijken</button></div><div class="list">${low.slice(0,5).map(x=>basicRow(x.title,`${x.amount} ${esc(x.unit)} in huis`,'Aanvullen','red')).join('')||empty('Voorraad is op peil')}</div></section></div>`
}

function renderPlanning(){const days=weekDays();return `<div class="week">${days.map(d=>`<section class="day ${d===todayISO()?'today':''}"><div class="day-name">${fmtDate(d,{weekday:'long'})}</div><div class="day-date">${new Date(d+'T12:00:00').getDate()}</div>${data.planning.filter(x=>x.date===d).sort((a,b)=>a.time.localeCompare(b.time)).map(x=>`<div class="meal"><small>${esc(x.time||'Hele dag')} · ${esc(x.person)}</small><strong>${esc(x.title)}</strong><button class="delete" data-delete="planning:${x.id}" aria-label="Verwijderen">×</button></div>`).join('')||'<p style="color:var(--muted)">Vrij</p>'}</section>`).join('')}</div>`}
function renderMeals(){const days=weekDays();return `<div class="week">${days.map(d=>`<section class="day ${d===todayISO()?'today':''}"><div class="day-name">${fmtDate(d,{weekday:'long'})}</div><div class="day-date">${new Date(d+'T12:00:00').getDate()}</div>${data.meals.filter(x=>x.date===d).map(x=>`<div class="meal"><small>${esc(x.type)}</small><strong>${esc(x.title)}</strong><button class="delete" data-delete="meals:${x.id}" aria-label="Verwijderen">×</button></div>`).join('')||'<p style="color:var(--muted)">Nog open</p>'}</section>`).join('')}</div>`}
function renderGroceries(){const groups=Object.groupBy(data.groceries,x=>x.category||'Overig');return `<div class="grid three">${Object.entries(groups).map(([group,items])=>`<section class="card"><div class="card-head"><h2>${esc(group)}</h2><span class="tag">${items.filter(x=>!x.done).length} open</span></div><div class="list">${items.map(groceryRow).join('')}</div></section>`).join('')||empty('Voeg jullie eerste boodschap toe')}</div>`}
function renderChores(){const done=data.chores.filter(x=>x.done).length;return `<section class="card" style="margin-bottom:18px"><div class="card-head"><div><h2>Deze ronde</h2><p style="color:var(--muted);margin:5px 0 0">${done} van ${data.chores.length} taken klaar</p></div><strong>${data.chores.length?Math.round(done/data.chores.length*100):0}%</strong></div><div class="progress"><span style="width:${data.chores.length?done/data.chores.length*100:0}%"></span></div></section><div class="grid two">${['Kees','Daphne','Samen'].map(person=>`<section class="card"><div class="card-head"><h2>${person}</h2><span class="tag ${person==='Samen'?'green':''}">${data.chores.filter(x=>x.person===person&&!x.done).length} open</span></div><div class="list">${data.chores.filter(x=>x.person===person).sort((a,b)=>a.done-b.done||a.due.localeCompare(b.due)).map(choreRow).join('')||empty('Geen taken')}</div></section>`).join('')}</div>`}
function renderStock(){return `<div class="grid three">${data.stock.sort((a,b)=>(a.amount<=a.min?-1:1)-(b.amount<=b.min?-1:1)).map(x=>{const low=+x.amount<=+x.min;return `<section class="card"><div class="card-head"><span class="tag ${low?'red':'green'}">${low?'Aanvullen':'Op peil'}</span><button class="delete" data-delete="stock:${x.id}">×</button></div><h2>${esc(x.title)}</h2><p style="color:var(--muted)">${esc(x.category)}</p><div style="display:flex;align-items:center;justify-content:space-between;margin-top:18px"><button class="secondary" data-stock="${x.id}:-1">−</button><strong style="font-size:1.5rem">${x.amount} <small style="font-size:.75rem;color:var(--muted)">${esc(x.unit)}</small></strong><button class="secondary" data-stock="${x.id}:1">＋</button></div><small style="display:block;text-align:center;color:var(--muted);margin-top:12px">Minimum: ${x.min}</small></section>`}).join('')||empty('Voeg producten toe die jullie willen bijhouden')}</div>`}
function renderIdeas(){return `<section class="card big-choice"><p class="eyebrow">Wat zullen we doen?</p><div id="choice" class="choice">Laat het toeval kiezen</div><button class="primary" data-random>🎲 Kies een idee</button></section><h2 style="margin:28px 0 14px">Jullie ideeën</h2><div class="idea-grid">${data.ideas.map(x=>`<article class="idea"><button class="delete" style="float:right" data-delete="ideas:${x.id}">×</button><div class="icon">${esc(x.icon||'♡')}</div><span class="tag orange">${esc(x.category)}</span><h3 style="margin:10px 0 0">${esc(x.title)}</h3><p>${esc(x.note)}</p></article>`).join('')||empty('Bewaar hier leuke ideeën voor samen')}</div>`}
function renderHome(){return `<div class="grid two">${['Onderhoud','Klus','Garantie','Woninginfo','Handleiding'].map(cat=>{const items=data.home.filter(x=>x.category===cat);if(!items.length)return '';return `<section class="card"><div class="card-head"><h2>${cat}</h2><span class="tag">${items.length}</span></div><div class="list">${items.map(x=>`<div class="list-item"><div class="item-main"><strong>${esc(x.title)}</strong><small>${esc(x.note)}${x.due?' · '+fmtDate(x.due):''}</small></div><button class="delete" data-delete="home:${x.id}">×</button></div>`).join('')}</div></section>`}).join('')||empty('Bewaar onderhoud, garanties en woninginformatie')}</div>`}
function renderTrips(){const upcoming=data.trips.sort((a,b)=>a.date.localeCompare(b.date));return `<div class="grid two"><section class="card"><div class="card-head"><h2>Komende momenten</h2><span class="tag orange">${upcoming.length}</span></div><div class="list">${upcoming.map(x=>`<div class="list-item"><div style="min-width:55px;text-align:center"><strong style="font-size:1.35rem">${new Date(x.date+'T12:00:00').getDate()}</strong><small style="display:block;color:var(--muted)">${fmtDate(x.date,{month:'short'})}</small></div><div class="item-main"><strong>${esc(x.title)}</strong><small>${esc(x.type)} · ${esc(x.note)}</small></div><button class="delete" data-delete="trips:${x.id}">×</button></div>`).join('')||empty('Nog geen reisplannen')}</div></section><section class="card"><div class="card-head"><h2>Reisoverzicht</h2></div><p style="color:var(--muted);line-height:1.55">Gebruik dit voor belangrijke reisdata, reserveringen, voorbereiding en paklijstitems. Alle informatie blijft op deze iPad staan.</p><button class="primary" onclick="openAdd()">＋ Reisitem</button></section></div>`}

function basicRow(title,sub,tag,color=''){return `<div class="list-item"><div class="item-main"><strong>${esc(title)}</strong><small>${esc(sub)}</small></div>${tag?`<span class="tag ${color}">${esc(tag)}</span>`:''}</div>`}
function groceryRow(x){return `<div class="list-item"><button class="check ${x.done?'done':''}" data-toggle="groceries:${x.id}" aria-label="Afvinken">${x.done?'✓':''}</button><div class="item-main"><strong class="${x.done?'done-text':''}">${esc(x.title)}</strong></div><button class="delete" data-delete="groceries:${x.id}">×</button></div>`}
function choreRow(x){return `<div class="list-item"><button class="check ${x.done?'done':''}" data-toggle="chores:${x.id}" aria-label="Afronden">${x.done?'✓':''}</button><div class="item-main"><strong class="${x.done?'done-text':''}">${esc(x.title)}</strong><small>${fmtDate(x.due)} · ${esc(x.repeat)}</small></div><span class="tag">${esc(x.person)}</span><button class="delete" data-delete="chores:${x.id}">×</button></div>`}
function weekDays(){const d=new Date();const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return Array.from({length:7},(_,i)=>addDays(d.toISOString().slice(0,10),i))}

function openAdd(){if(current==='today')return;const cfg=formConfig[current];document.querySelector('#dialogTitle').textContent=cfg.title;document.querySelector('#formFields').innerHTML=cfg.fields.map(([name,label,type,opts])=>`<div class="field"><label for="f-${name}">${label}</label>${type==='select'?`<select id="f-${name}" name="${name}">${opts.map(o=>`<option>${o}</option>`).join('')}</select>`:type==='textarea'?`<textarea id="f-${name}" name="${name}"></textarea>`:`<input id="f-${name}" name="${name}" type="${type}" ${['title','date'].includes(name)?'required':''} ${name==='date'||name==='due'?`value="${todayISO()}"`:''}>`}</div>`).join('');document.querySelector('#itemDialog').showModal()}
function handleSubmit(e){e.preventDefault();const fd=Object.fromEntries(new FormData(e.target));if(!fd.title)return;['amount','min'].forEach(k=>{if(k in fd)fd[k]=Number(fd[k])});if(current==='groceries'||current==='chores')fd.done=false;data[current].push({id:id(),...fd});save();document.querySelector('#itemDialog').close();render();toast('Toegevoegd')}
function downloadBackup(file){const a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Back-up opgeslagen')}
async function exportBackup(){
 const file=new File([JSON.stringify(data,null,2)],`samen-thuis-backup-${todayISO()}.json`,{type:'application/json'});
 const isiPad=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
 if(isiPad&&navigator.share&&navigator.canShare?.({files:[file]})){
  try{await navigator.share({files:[file],title:'Samen Thuis back-up',text:'Bewaar dit bestand via Bewaar in Bestanden in iCloud Drive, zodat het ook op de laptop staat.'});toast('Back-up gedeeld');return}catch(err){if(err?.name==='AbortError')return}
 }
 downloadBackup(file)
}
function importBackup(file){const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result);if(!parsed||typeof parsed!=='object')throw Error();data={...structuredClone(initialData),...parsed};save();render();toast('Back-up hersteld')}catch{toast('Dit bestand is geen geldige back-up')}};reader.readAsText(file)}

document.addEventListener('click',e=>{
 if(e.target.closest('[data-close-dialog]')){document.querySelector('#itemDialog').close();return}
 const view=e.target.closest('[data-view]');if(view){navigate(view.dataset.view);return}
 const del=e.target.closest('[data-delete]');if(del){const [type,itemId]=del.dataset.delete.split(':');data[type]=data[type].filter(x=>x.id!==itemId);save();render();return}
 const toggle=e.target.closest('[data-toggle]');if(toggle){const [type,itemId]=toggle.dataset.toggle.split(':');const item=data[type].find(x=>x.id===itemId);item.done=!item.done;save();render();return}
 const stock=e.target.closest('[data-stock]');if(stock){const [itemId,amount]=stock.dataset.stock.split(':');const item=data.stock.find(x=>x.id===itemId);item.amount=Math.max(0,+item.amount+Number(amount));save();render();return}
 if(e.target.closest('[data-random]')){if(!data.ideas.length)return;const item=data.ideas[Math.floor(Math.random()*data.ideas.length)];document.querySelector('#choice').textContent=`${item.icon||'♡'} ${item.title}`}
 const action=e.target.closest('[data-action]')?.dataset.action;if(action==='backup')exportBackup();if(action==='restore')document.querySelector('#restoreInput').click()
});
document.querySelector('#addBtn').addEventListener('click',openAdd);
document.querySelector('#laptopSaveBtn').addEventListener('click',exportBackup);
document.querySelector('#itemForm').addEventListener('submit',handleSubmit);
document.querySelector('#restoreInput').addEventListener('change',e=>e.target.files[0]&&importBackup(e.target.files[0]));
document.querySelector('#eyebrow').textContent=new Intl.DateTimeFormat('nl-NL',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
setupNav();render();
